### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by imranismail** [rbCAS/CASino#114]
I have setup everything properly.. but it gives me this error `NoMethodError (undefined method `underscore' for nil:NilClass):`

here are my settings

**database.yml**
```
default: &default
  username:
  password:
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  host: localhost
  pool: 5

production:
  <<: *default
  database: CASinoApp_production

development:
  <<: *default
  database: CASinoApp_development

test:
  <<: *default
  database: CASinoApp_test

```

**cas.yml**

```
development:
  frontend:
    sso_name: "MaGIC Connect"
    footer_text: "Powered by <a href='http://mymagic.my/'>MaGIC</a>"
  authenticators:
    my_company_sql_database:
    authenticator: "ActiveRecord"
    options:
      connection:
        adapter: "postgresql"
        encoding: "unicode"
        timeout: 5000
        host: "localhost"
        pool: 5
        database: "CASinoApp_development"
      table: "users"
      username_column: "username"
      password_column: "password_digest"
      extra_attributes:
        email: "email"
        fullname: "fullname"

########################################
# LDAP
########################################
#    my_company_ldap:
#      authenticator: 'LDAP'
#      options:
#        host: 'localhost'
#        port: 636
#        base: 'ou=people,dc=example,dc=com'
#        username_attribute: 'uid'
#        encryption: 'simple_tls'
#        extra_attributes:
#          email: 'mail'
#          fullname: 'displayname'

########################################
# SQL (ActiveRecord authenticator)
########################################
#    my_company_sql_database:
#      authenticator: "ActiveRecord"
#      options:
#        connection:
#          adapter: "mysql2"
#          host: "localhost"
#          username: "casino"
#          password: "secret"
#          database: "users"
#        table: "users"
#        username_column: "username"
#        password_column: "password"
#        extra_attributes:
#          email: "email_database_column"
#          fullname: "displayname_database_column"

```

**and heres the stack trave**

```
Started POST "/login" for 127.0.0.1 at 2015-06-17 03:13:58 +0800
Processing by CASino::SessionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"cHwIVv2UA5THv5/FruntJfB4PfnZP1MZS/psdU75Rb0=", "lt"=>"LT-14344820346818-IMAhWH3k758CSiI0Z6C55cf06u6z0FfWJkiueJJd", "username"=>"imranismail", "password"=>"[FILTERED]", "rememberMe"=>"1", "button"=>""}
  CASino::LoginTicket Load (0.4ms)  SELECT  "casino_login_tickets".* FROM "casino_login_tickets"  WHERE "casino_login_tickets"."ticket" = 'LT-14344820346818-IMAhWH3k758CSiI0Z6C55cf06u6z0FfWJkiueJJd' LIMIT 1
Login ticket 'LT-14344820346818-IMAhWH3k758CSiI0Z6C55cf06u6z0FfWJkiueJJd' successfully validated
  SQL (2.1ms)  DELETE FROM "casino_login_tickets" WHERE "casino_login_tickets"."id" = 6
Completed 500 Internal Server Error in 5ms

NoMethodError (undefined method `underscore' for nil:NilClass):
  casino (4.0.1) app/processors/casino/authentication_processor.rb:61:in `parse_name'
  casino (4.0.1) app/processors/casino/authentication_processor.rb:48:in `load_authenticator'
  casino (4.0.1) app/processors/casino/authentication_processor.rb:38:in `block (2 levels) in authenticators'
  casino (4.0.1) app/processors/casino/authentication_processor.rb:32:in `each'
  casino (4.0.1) app/processors/casino/authentication_processor.rb:32:in `block in authenticators'
  casino (4.0.1) app/processors/casino/authentication_processor.rb:31:in `tap'
  casino (4.0.1) app/processors/casino/authentication_processor.rb:31:in `authenticators'
  casino (4.0.1) app/processors/casino/authentication_processor.rb:8:in `validate_login_credentials'
  casino (4.0.1) app/controllers/casino/sessions_controller.rb:23:in `create'
  actionpack (4.1.8) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.1.8) lib/abstract_controller/base.rb:189:in `process_action'
  actionpack (4.1.8) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.1.8) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.1.8) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:113:in `call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.8) lib/active_support/callbacks.rb:149:in `call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.8) lib/active_support/callbacks.rb:149:in `call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.8) lib/active_support/callbacks.rb:149:in `call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
  activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:229:in `call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:229:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:166:in `block in halting'
  activesupport (4.1.8) lib/active_support/callbacks.rb:86:in `call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:86:in `run_callbacks'
  actionpack (4.1.8) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.8) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.1.8) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.8) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.8) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.8) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.8) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.1.8) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.1.8) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.8) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.1.8) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.1.8) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.8) lib/action_controller/metal.rb:232:in `block in action'
  actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:82:in `call'
  actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:50:in `call'
  actionpack (4.1.8) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:678:in `call'
  railties (4.1.8) lib/rails/engine.rb:514:in `call'
  railties (4.1.8) lib/rails/railtie.rb:194:in `public_send'
  railties (4.1.8) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.1.8) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `each'
  actionpack (4.1.8) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.8) lib/action_dispatch/routing/route_set.rb:678:in `call'
  http_accept_language (2.0.5) lib/http_accept_language/middleware.rb:14:in `call'
  rack (1.5.3) lib/rack/etag.rb:23:in `call'
  rack (1.5.3) lib/rack/conditionalget.rb:35:in `call'
  rack (1.5.3) lib/rack/head.rb:11:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.3) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.3) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.1.8) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.8) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.8) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.8) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.3) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.3) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.8) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.3) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.3) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.8) lib/rails/engine.rb:514:in `call'
  railties (4.1.8) lib/rails/application.rb:144:in `call'
  rack (1.5.3) lib/rack/lock.rb:17:in `call'
  rack (1.5.3) lib/rack/content_length.rb:14:in `call'
  rack (1.5.3) lib/rack/handler/webrick.rb:60:in `service'
  /Users/imranismail/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
  /Users/imranismail/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
  /Users/imranismail/.rbenv/versions/1.9.3-p194/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
```
